version: "3.10"
services:
  web:
    image: movieland
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000
    depends_on:
     - postgresql
     - redis
    env_file:
     - .env
  postgresql:
   container_name: pg-db
   image: postgres:15
   restart: always
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=MovieLandDatabase
   ports:
     - '5432:5432'
   volumes: 
     - db:/var/lib/postgresql/data
  redis:
    container_name: redis_db
    image: redis
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

 
volumes:
 db:
  driver: local
 cache:
  driver: local



